language: python
python:
  - "2.7"

before_install:
  - "npm install -g bower"

# command to install dependencies
install:
  - "pip install Fabric path.py"
  - "fab make_test_env"
  - "fab dependencies:test"

# command to run tests
script:
  - "fab test_coverage"
  - "fab docs"

after_success:
  - coveralls
